export const palavrass = [
    // 0 - 69
    'VÉU', 'GIZ', 'IOIÔ', 'CHIP', 'CRUZ', //5
    'IATE', 'GIBI', 'URNA', 'LIXA', 'ANEL', //10
    'BOINA', 'GAITA', 'SUNGA', 'VIOLA', 'SHORT', //15
    'RÉGUA', 'TIARA', 'MODEM', 'HARPA', 'FOICE', //20
    'CD', 'DOMINÓ', 'ESTOJO', 'PUNHAL', 'ESPETO', //25
    'TALHER', 'SUÉTER', 'FRASCO', 'DIÁRIO', 'ENXADA', //30
    'ANDAIME', 'AVENTAL', 'GRANADA', 'INCENSO', 'FLANELA', //35
    'CORNETA', 'CRISTAL', 'GALOCHA', 'MARRETA', 'NAVALHA', //40
    'REGADOR', 'PENEIRA', 'TAMANCO', 'SERINGA', 'VOLANTE', //45
    'CACHECOL', 'CAMISOLA', 'HIDRANTE', 'POLTRONA', 'SANDÁLIA', //50
    'CLARINETE', 'FILMADORA', 'GUIRLANDA', 'FIGURINHA','ESPANADOR', //55
    'AMPULHETA', 'GARRAFA PET', 'FIO DENTAL', 'MARIONETE', 'MINISSAIA', //60
    'SAPATILHA', 'PALITEIRO', 'LUMINÁRIA', 'TABULEIRO', 'VÍDEO GAME', //65
    'PERGAMINHO', 'PARAQUEDAS', 'LIXA DE UNHA', 'GUARDA-SOL', 'PIERCING', //70

    // 70 - 139
    'BODE', 'SIRI', 'BOTO', 'ORCA', 'CUCO', // 5
    'MULA', 'URSO', 'RENA', 'RATO', 'ALCE', //10
    'SAPO', 'PERU', 'ATUM', 'LULA', 'JACU', //15
    'CERVO', 'CUTIA', 'POLVO', 'PANDA', 'CORVO', //20
    'LINCE', 'CISNE', 'HIENA', 'BAGRE', 'ROUXINOL', //25
    'LONTRA', 'GAZELA', 'ABUTRE', 'CAVALO', 'CHACAL', //30
    'BAIACU', 'ENGUIA', 'PICA-PAU', 'TAINHA', 'CASTOR', //35
    'GORILA', 'GIRINO', 'CADELA', 'PARDAL', 'COELHO', //40
    'CABRITO', 'MARRECO', 'JUMENTO', 'CODORNA', 'CANGURU', //45
    'LAGARTA', 'CEGONHA', 'BABUÍNO', 'CACATUA', 'CARACOL', //50
    'JOANINHA', 'CACHORRO', 'FLAMINGO', 'ANTÍLOPE', 'CAPIVARA', //55
    'LIBÉLULA', 'CARAMUJO', 'SARACURA', 'TUCUNARÉ', 'SURUCUCU', //60
    'SAPO-BOI', 'ÁGUA-VIVA', 'CHINCHILA', 'VAGA-LUME', 'BEM-TE-VI', //65
    'PEIXE-LUA', 'CHIMPANZÉ', 'BORBOLETA', 'URSO-POLAR', 'URSO-PARDO', //70

    //140 - 209
    'KIWI', 'DOCE DE GOIABA', 'SOPA', 'ALHO', 'FIGO', //5
    'AIPIM', 'CURAU', 'AVEIA', 'SUSHI', 'PUDIM', //10
    'AVELÃ', 'PIZZA', 'PEQUI', 'COUVE', 'CAQUI', //15
    'ARROZ', 'QUIBE', 'MILHO', 'FEIJÃO', 'MANGA', //20
    'FAROFA', 'MOUSSE', 'CEBOLA', 'AMEIXA', 'RISOTO', //25
    'PICLES', 'INHAME', 'PIPOCA', 'TACACÁ', 'CUSCUZ', //30
    'CHURROS', 'CHEDDAR', 'BROWNIE', 'CANJICA', 'BOLACHA', //35
    'CUPCAKE', 'CEBOLA ROXA', 'ESFIRRA', 'SUSPIRO', 'PAMONHA', //40
    'COXINHA', 'KETCHUP', 'REPOLHO', 'PICANHA', 'ABACATE', //45
    'AMENDOIM', 'BRÓCOLIS', 'GENGIBRE', 'BEIJINHO', 'RAPADURA', //50
    'REQUEIJÃO', 'CHANTILLY', 'CARAMBOLA', 'CHOCOLATE', 'BOLO DE MILHO', //55
    'ARROZ DOCE', 'PÃO DE ALHO', 'MAÇÃ VERDE', 'YAKISOBA', 'ABOBRINHA', //60
    'UVA PASSA', 'PÃO DE MEL', 'TALHARIM', 'FEIJOADA', 'PARMESÃO', //65
    'PANQUECA', 'BOLO DE FUBÁ', 'CARAMELO', 'CONTRA FILÉ', 'BALA DE GOMA', //70

    //210 - 279
    'MIAR', 'ROER', 'ARAR', 'AMAR', 'ORAR', //5
    'ACHAR', 'UIVAR', 'ADIAR', 'SUBIR', 'MIRAR', //10
    'COMER', 'FREAR', 'JOGAR', 'LATIR', 'OUVIR', //15
    'CURTIR', 'CUIDAR', 'FATIAR', 'EDUCAR', 'GRITAR', //20
    'TECLAR', 'TATUAR', 'SALVAR', 'SEMEAR', 'POSTAR', //25
    'CHORAR', 'CHAMAR', 'LACRAR', 'JANTAR', 'FILMAR', //30
    'AQUECER', 'APROVAR', 'AGENDAR', 'EVOLUIR', 'ESFRIAR', //35
    'NAVEGAR', 'PLANTAR', 'LEVITAR', 'FOFOCAR', 'ESCALAR', //40
    'NAMORAR', 'PEDALAR', 'QUEBRAR', 'REBOCAR', 'LEILOAR', //45
    'BLOQUEAR', 'CARIMBAR', 'CONGELAR', 'DESENHAR', 'HIDRATAR', //50
    'ESPIAR', 'SAMBAR', ' JULGAR', 'ALMOÇAR', 'COLORIR', //55
    'DIRIGIR', 'DEMOLIR', 'CRESCER', 'DEMITIR', 'VENCER', //60
    'DIVIDIR', 'ENGOLIR', 'PROIBIR', 'REDUZIR', 'DESPEDIR', //65
    'CONSTRUIR', 'PERSEGUIR', 'TELEFONAR', 'DESCOLORIR', 'PARABENIZAR', //70

    //280 - 349
    'ATOR', 'JUIZ', 'GARI', 'PADRE', 'VIGIA', //5
    'MODELO', 'BARMAN', 'CHOFER', 'FREIRA', 'PERITO', //10
    'PINTOR', 'MÉDICO', 'PILOTO', 'XERIFE', 'FISCAL', //15
    'BIÓLOGO', 'GINASTA', 'COPEIRO', 'TAXISTA', 'MORDOMO', //20
    'MOTOBOY', 'LOCUTOR', 'PADEIRO', 'TENENTE', 'DIRETOR', //25
    'SOLDADO', 'TEÓLOGO', 'COVEIRO', 'ZELADOR', 'MAESTRO', //30
    'DIARISTA', 'LENHADOR', 'PEDAGOGO', 'MANICURE', 'PEDIATRA', //35
    'PEDREIRO', 'PEIXEIRO', 'POLICIAL', 'PESCADOR', 'SUSHIMAN', //40
    'CIENTISTA', 'ENCANADOR', 'ALPINISTA', 'BAILARINA', 'FAXINEIRO', //45
    'COZINHEIRO', 'COMEDIANTE', 'PIPOQUEIRO', 'MAQUINISTA', 'PSIQUIATRA', //50
    'PIZZAIOLO', 'TERAPEUTA', 'AÇOUGUEIRO', 'ADESTRADOR', 'CARTUNISTA', //55 
    'VEREADOR', 'PREFEITO', 'PIANISTA', 'VENDEDOR', 'BILHETEIRO', //60
    'PROFESSOR', 'PAISAGISTA', 'JARDINEIRO', 'OFFICE-BOY', 'SECRETÁRIA', //65
    'RADIALISTA', 'ESTETICISTA', 'PRESIDENTE', 'DJ', 'GEÓLOGO', //70

    //350 -419
    'ALTO', 'LEVE', 'SUJO', 'RICO', 'NOVO', //5
    'FELIZ', 'FORTE', 'LIMPO', 'LOUCO', 'VESGO', //10
    'VELHO', 'LENTO', 'POBRE', 'CHATO', 'MACIO', //15
    'GRANDE', 'QUENTE', 'RÁPIDO', 'BONITO', 'QUIETO', //20
    'ESCURO', 'CALADO', 'TÍMIDO', 'CARECA', 'OLEOSO', //25
    'GELADO', 'FEBRIL', 'DESTRO', 'MURCHO', 'CAFONA', //30
    'FAMINTO', 'CANIBAL', 'CURIOSO', 'GIGANTE', 'MEDROSO', //35
    'NERVOSO', 'REDONDO', 'DEITADO', 'ANIMADO', 'RISONHO', //40
    'CIUMENTO', 'CORCUNDA', 'GRUDENTO', 'GRISALHO', 'CACHEADO', //45
    'ARREPIADO', 'DIVERTIDO', 'CONECTADO', 'CARINHOSO', 'PERFUMADO', //50
    'DOIDO', 'DÓCIL', 'FEROZ', 'SUADO', 'ABATIDO', //55
    'CANHOTO', 'AMASSADO', 'CARNÍVORO', 'DALTÔNICO', 'DESLIGADO', //60
    'BLOQUEADO', 'DISTRAÍDO', 'ENFEITADO', 'ENGRAÇADO', 'ENTEDIADO', //65
    'EMPOLGADO', 'SORRIDENTE', 'SONÂMBULO', 'ROMÂNTICO', 'SOLITÁRIO', //70

    //420 - 489
    'AFEGANISTÃO', 'ÁFRICA DO SUL', 'ALBÂNIA', 'ARGENTINA', 'ÁUSTRIA', //5
    'ALEMANHA', 'ANDORRA', 'ANGOLA', 'ARMÊNIA', 'ARÁBIA SAUDITA', //10
    'BAHAMAS', 'BÉLGICA', 'BANGLADESH', 'BRASIL', 'CANADÁ', //15
    'DINAMARCA', 'ETIÓPIA', 'ESPANHA', 'FINLÂNDIA', 'GUATEMALA', //20
    'HAITI', 'IÊMEN', 'IRÃ', 'JAMAICA', 'JAPÃO', //25
    'KUWAIT', 'LETÔNIA', 'MIANMAR', 'MALÁSIA', 'NOVA ZELÂNDIA', //30
    'OMÃ', 'PAÍS DE GALES', 'PARAGUAI', 'PERU', 'QUÊNIA', //35
    'RÚSSIA', 'RUANDA', 'SENEGAL', 'SERRA LEOA', 'SRI LANKA', //40
    'TUVALU', 'TAJIQUISTÃO', 'TURQUIA', 'VENEZUELA', 'VIETNÃ', //45
    'ZÂMBIA', 'ZIMBÁBUE', 'VATICANO', 'URUGUAI', 'PORTUGAL', //50
    'SURINAME', 'TAIWAN', 'UCRÂNIA', 'CHINA', 'SINGAPURA', //55
    'BOLÍVIA', 'BELIZE', 'BURKINA FASO', 'BUTÃO', 'CABO VERDE', //60
    'CROÁCIA', 'CUBA', 'COLÔMBIA', 'COREIA DO SUL', 'COSTA RICA', //65
    'EL SALVADOR', 'ESLOVÁQUIA', 'ESLOVÊNIA', 'FILIPINAS', 'NÍGER' //70
]